version: "3"
services:
    frontend:
        container_name: react-app
        build:
            context: ./frontend/vehicles
            dockerfile: Dockerfile
        image: sammedkamate/react-app
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/vehicles:/usr/src/app
    backend:
        container_name: node-web-app
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: sammedkamate/node-web-app
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/usr/src/app